spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  datasource:
    url: jdbc:mysql://localhost:3306/status_db?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: '!qwer567'
    driver-class-name: com.mysql.cj.jdbc.Driver
