branch-defaults:
  main:
    environment: voxkorea-env
global:
  application_name: voxkorea-env
  branch: null
  default_ec2_keyname: voxtest
  default_platform: Corretto 21 running on 64bit Amazon Linux 2023
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
